# Generated by Django 3.2.3 on 2021-05-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papich_media_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediacontent',
            options={'verbose_name_plural': 'Media Content'},
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='filepath',
            field=models.FilePathField(default='defaults/default.mp3', verbose_name='Path to content file'),
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='Likes amount'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='displayed_name',
            field=models.CharField(max_length=60, verbose_name='Displayed name'),
        ),
    ]
