# Generated by Django 3.2.3 on 2021-05-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papich_media_api', '0002_auto_20210519_1854'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediacontent',
            options={'verbose_name': 'Media Content', 'verbose_name_plural': 'Media Content'},
        ),
    ]
