# Generated by Django 3.2.3 on 2021-05-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papich_media_api', '0003_alter_mediacontent_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='filepath',
            field=models.CharField(max_length=1000, verbose_name='Path to content file'),
        ),
    ]
