# Generated by Django 3.2.3 on 2021-05-31 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('papich_media_api', '0004_alter_mediacontent_filepath'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('external_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram id')),
                ('name', models.CharField(max_length=60, verbose_name='Telegram name')),
                ('is_moderator', models.BooleanField(default=False, verbose_name='Has Moderator rights')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='papich_media_api.user'),
        ),
    ]
