# Generated by Django 3.2.3 on 2021-06-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papich_media_api', '0006_auto_20210602_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='likers',
            field=models.ManyToManyField(related_name='liked_media_content', to='papich_media_api.User', verbose_name='Users, who hit like'),
        ),
    ]
