# Generated by Django 3.2.3 on 2021-06-02 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papich_media_api', '0007_alter_mediacontent_likers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacontent',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='liked_media_content', to='papich_media_api.User', verbose_name='Users, who hit like'),
        ),
    ]
